
const types = {

    GET_RECIPIENT_EVENTS_REQUEST: 'GET_RECIPIENT_EVENTS_REQUEST',
    GET_RECIPIENT_EVENTS_SUCCESS: 'GET_RECIPIENT_EVENTS_SUCCESS',
    GET_RECIPIENT_EVENTS_FAILURE: 'GET_RECIPIENT_EVENTS_FAILURE',

    GET_RECIPIENTS_REQUEST: 'GET_RECIPIENTS_REQUEST',
    GET_RECIPIENTS_SUCCESS: 'GET_RECIPIENTS_SUCCESS',
    GET_RECIPIENTS_FAILURE: 'GET_RECIPIENTS_FAILURE',

    GET_RECIPIENT_DATES_REQUEST: 'RECIPIENT_DATES_REQUEST',
    GET_RECIPIENT_DATES_SUCCESS: 'RECIPIENT_DATES_SUCCESS',
    GET_RECIPIENT_DATES_FAILURE: 'RECIPIENT_DATES_FAILURE',

    GET_EVENTS_RECIPIENT_BY_DATE_REQUEST: 'GET_EVENTS_RECIPIENT_BY_DATE_REQUEST',
    GET_EVENTS_RECIPIENT_BY_DATE_SUCCESS: 'GET_EVENTS_RECIPIENT_BY_DATE_SUCCESS',
    GET_EVENTS_RECIPIENT_BY_DATE_FAILURE: 'GET_EVENTS_RECIPIENT_BY_DATE_FAILURE',

    GET_EVENTS_RECIPIENT_BY_EVENT_TYPE_REQUEST: 'GET_EVENTS_RECIPIENT_BY_EVENT_TYPE_REQUEST',
    GET_EVENTS_RECIPIENT_BY_EVENT_TYPE_SUCCESS: 'GET_EVENTS_RECIPIENT_BY_EVENT_TYPE_SUCCESS',
    GET_EVENTS_RECIPIENT_BY_EVENT_TYPE_FAILURE: 'GET_EVENTS_RECIPIENT_BY_EVENT_TYPE_FAILURE'
};




export default types;